EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_gem:
        rubocop-rails-omakase: rubocop.yml
      Layout/TrailingEmptyLines:
        Enabled: false
