# Reek configuration. See https://github.com/troessner/reek

exclude_paths:
  - db/migrate

detectors:
  BooleanParameter:
    exclude:
      - AlertComponent#initialize        # dismissible flag for optional close button
      - Auth::LinkComponent#initialize    # centered flag for optional layout styling
  InstanceVariableAssumption:
    exclude:
      - PasswordsController              # @user set by before_action
      - UsersController                   # @user set in actions for views
  UtilityFunction:
    exclude:
      - PasswordsMailerPreview#reset      # previews don't use instance state by design
